services:
  portainer_agent:
    image: portainer/agent:2.27.1
    container_name: portainer_agent
    networks:
      - portainer_agent_network
    ports:
      - "9001:9001"
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host

networks:
  portainer_agent_network:
    driver: overlay
