services:
  registry-ui:
    image: quiq/registry-ui:latest
    container_name: registry_ui
    restart: unless-stopped
    environment:
      - X-WEBAUTH-USER=${X-WEBAUTH-USER}
    networks:
      -  nat:
    ports:
      - 8000:8000
###################################################      
  registry-server:
    image: registry:latest
    restart: unless-stopped
    container_name: registry-server    
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"      
    volumes:
      - /path/to/your-containers:/var/lib/registry
      - /auth:/auth
    ports:
      - 5000:5000
    networks:
      -  nat
################################      
networks:
    nat:
        external: true