services:
  bind9:
    image: docker.io/ubuntu/bind9:9.20-24.10_edge
    container_name: bind9
    environment:
      - DEBUG=true  #optional
      - BIND9_USER=root
      - TZ=America/Los_Angelos
    ports:
      - "53:53"
    volumes:
      - /etc/bind/:/etc/bind/
      - /var/cache/bind:/var/cache/bind
      - /var/lib/bind:/var/lib/bind
    restart: unless-stopped
    networks:
      - nat
    healthcheck:
      test: ["CMD", "dig", "+short", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  nat:
   external: true