---
services:
  gitlab:
    image: gitlab/gitlab-ce:17.9.1-ce.0
    container_name: gitlab
    shm_size: '256m'
    environment: {}
    networks:
      - nat
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
#    ports:
#      - "80:80"
#      - "443:443"
#      - '2424:22' #change as needed for whatever port for tcp routers config check traefik templates folder  
    labels:
      - traefik.enable=true
      - traefik.http.services.gitlab.loadbalancer.server.port=80
      - traefik.http.routers.gitlab.service=gitlab
      - traefik.http.routers.gitlab.rule=Host(`your-gitlab-fqdn`)
      - traefik.http.routers.gitlab.entrypoints=websecure
      - traefik.http.routers.gitlab.tls=true
      - traefik.http.routers.gitlab.tls.certresolver=cloudflare
      - "traefik.docker.network=nat" 
# tcp routers for ssh port 2424 or whatever you chose
      - traefik.tcp.routers.gitlab-tcp.rule=HostSNI(`*`)
      - traefik.tcp.routers.gitlab-tcp.entrypoints=git
      - traefik.tcp.routers.gitlab-tcp.service=gitlab-tcp
      - traefik.tcp.services.gitlab-tcp.loadbalancer.server.port=2424  
#registry (optional) -------------------------------------------------------------->
#      - traefik.http.services.registry.loadbalancer.server.port=5678
#      - traefik.http.services.registry.loadbalancer.server.scheme=http
#      - traefik.http.routers.registry.service=registry
#      - traefik.http.routers.registry.rule=Host(`your-registry-fqdn`)
#      - traefik.http.routers.registry.entrypoints=websecure
#      - traefik.http.routers.registry.tls=true
#      - traefik.http.routers.registry.tls.certresolver=cloudflare
# <---------------------------------------------------------------------------  

#pages (optional)   --------------------------------------------------------->
#      traefik.http.routers.pages.rule=HostRegexp(`^(?i)(?:[a-zA-Z0-9-]+\.)*pages\.example\.com$`)  # Wildcard domain for GitLab Pages
#      - "traefik.http.routers.gitlab-pages.entrypoints=web-secure"  # Route over HTTPS
#      - "traefik.http.routers.gitlab-pages.tls=true"  # Enable TLS
#      - "traefik.http.routers.gitlab-pages.tls.certresolver=letsencrypt"  # Use Let's Encrypt for TLS
#      - "traefik.http.services.gitlab-pages.loadbalancer.server.port=8090"  # Point to GitLab Pages service (port 8090)
# <---------------------------------------------------------------------------
    restart: unless-stopped
networks:
  nat:
    external: true