worker_processes 1;

events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            record off;

            # (optional) Replace with your RTMP server address
            push rtmp://ip-address/live;  
        }
    }
}

# Optional: Disable HTTP access
http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        
        # This will return a 403 Forbidden response for any HTTP requests
        location / {
            return 403;   
        }
    }
}