services:
  redis:
    container_name: paperless_redis
    image: 'redis:7.4'
    volumes:
      - 'paperless-redis:/data'
    networks:
       - nat
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 10s
      retries: 3
###############################################################################################      
  paperless:
    image: 'paperlessngx/paperless-ngx:latest'
    networks:
       - nat
    container_name: paperless
    # ports:
    #  - 8000:8000
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-fs'
        - '-S'
        - '--max-time'
        - '2'
        - 'http://localhost:8000'
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - 'paperless-data:/usr/src/paperless/data'
      - 'paperless-media:/usr/src/paperless/media'
      - './export:/usr/src/paperless/export'
      -  './consume:/usr/src/paperless/consume'
    environment:
      - 'PAPERLESS_URL=${SERVICE_FQDN_PAPERLESS_8000}'
      - 'PAPERLESS_ADMIN_PASSWORD=${SERVICE_PASSWORD_PAPERLESS}'
      - 'PAPERLESS_ADMIN_USER=${SERVICE_USER_PAPERLESS}'
      - 'PAPERLESS_REDIS=redis://redis:6379'
      - 'PAPERLESS_SECRET_KEY=${SERVICE_REALBASE64_64_PAPERLESS}'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=Host(`${SERVICE_FQDN_PAPERLESS_8000?Replace('http://','').Replace('https://','')}`)" # Strip protocol from FQDN
      - "traefik.http.routers.paperless.entrypoints=websecure" # Or web if not using TLS
      - "traefik.http.routers.paperless.tls.certresolver=letsencrypt" # Replace letsencrypt with your certresolver name if different
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
networks:
  nat:
    external: true
