services:
  redis:
    container_name: paperless_redis
    image: 'redis:7.4'
    restart: always
    volumes:
      - 'paperless-redis:/data'
    networks:
       - nat
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 10s
      retries: 3
###############################################################################################      
  paperless:
    image: 'paperlessngx/paperless-ngx:latest'
    networks:
      - nat
    container_name: paperless
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-fs'
        - '-S'
        - '--max-time'
        - '2'
        - 'http://localhost:8000'
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - './paperless-data:/usr/src/paperless/data'
      - './paperless-media:/usr/src/paperless/media'
      - './export:/usr/src/paperless/export'
      -  './consume:/usr/src/paperless/consume'
    environment:
      - 'PAPERLESS_URL=${SERVICE_FQDN_PAPERLESS_8000}'
      - 'PAPERLESS_ADMIN_PASSWORD=${SERVICE_PASSWORD_PAPERLESS}'
      - 'PAPERLESS_ADMIN_USER=${SERVICE_USER_PAPERLESS}'
      - 'PAPERLESS_REDIS=redis://redis:6379'
      - 'PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY}'
#    labels:   # (optional only for using traefik) ------>
#      - "traefik.enable=true"
#      - "traefik.http.routers.paperless.entrypoints=websecure"
#      - "traefik.http.routers.paperless.rule=Host(`paperless.example.com`)" # Replace with your desired hostname
#      - "traefik.http.routers.paperless.tls=true"
#      - "traefik.http.routers.paperless.tls.certresolver=cloudflare" # Replace with your cert resolver name
#      - "traefik.http.services.paperless.loadbalancer.server.port=8000"    
#      - "traefik.docker.network=nat" 
#      - "traefik.http.routers.paperless.service=paperless"  
#      - "com.centurylinklabs.watchtower.enable=true"  # (optional if using watchtower for updates)
#      - "traefik.http.routers.paperless.middlewares=authentik@file" # (optional if using authentik or basic auth to protect your site)
networks:
  nat:
    external: true 
