services:
  filebrowser:
    image: 'filebrowser/filebrowser:v2.32.0-s6'
    container_name: filebrowser
    restart: unless-stopped
    environment:
      - PGID=$(PGID)
      - PUID=$(PUID)
      - TZ=AMERICA/LOS_ANGELOS
    volumes:
      - './settings.json:/config/settings.json'
      - '/:/srv:rw'
#    ports:
#      - 8080:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - nat
    labels: # (optional only for using traefik) ------>
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.example.com`)" # Replace with your desired hostname
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.tls.certresolver=cloudflare" # Replace with your cert resolver name
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"    
      - "traefik.docker.network=nat" 
      - "traefik.http.routers.filebrowser.service=filebrowser"  
#      - "com.centurylinklabs.watchtower.enable=true"  # (optional if using watchtower for updates)
#      - "traefik.http.routers.filebrowser.middlewares=authentik@file" # (optional if using authentik or basic auth to protect your site)
network:
  nat:
    external: true           