services:
  socat:
    image: alpine/socat
    container_name: socat-docker
    ports:
      - "2376:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: TCP-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    restart: always
    networks:
      -  nat
networks:
    nat:
      external: true