global:
  sendAnonymousUsage: false
#####################################
log:
  level: INFO    # (optional for testing) DEBUG
  format: common
##################################
accessLog: {}
api:
  dashboard: true
  debug: true
  insecure: true
###################################
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare
  metrics:
    address: ":8082"
  git:
    address: ":2424"
###################################################
metrics:
  prometheus:
    entryPoint: metrics
    addServicesLabels: true # Add service labels to metrics
    addRoutersLabels: true  # Add router labels to metrics
###################################################################
serversTransport:
  insecureSkipVerify: true
#################################################################
providers:
#  swarm:     # (optional if you have a swarm)
#    exposedByDefault: false
#    watch: true
  docker:    # (required)
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
  file:      # (optional)
    directory: /config
    watch: true
#############################################################
pilot:
  token: xxxx

experimental:
  plugins:
    traefik-real-ip:
      modulename: github.com/soulbalz/traefik-real-ip
      version: v1.0.3
#################################################################      
certificatesResolvers:
  letsencrypt:
    acme:
      email: example@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
  cloudflare:
    acme:
      email: example@example.com
      storage: acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
     # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: cloudflare
 #       disablePropagationCheck: true
#        delayBeforeCheck: 120s
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
  # Uncomment the following if you want to use Buypass as an alternative CA
  buypass:
    acme:
      email: dlynton01@outlook.com
      storage: /etc/dokploy/traefik/dynamic/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 60
      caServer: https://api.buypass.com/acme/directory # buypass if let's encrypt is down          
#####################################################################################################
# Tracing Configuration
tracing:
  serviceName: traefik  # Name shown in the tracing backend
  jaeger:
    samplingServerURL: http://localhost:5778/sampling  # Jaeger sampling server URL
    localAgentHostPort: localhost:6831  # Jaeger agent host and port
    samplingType: const  # Sampling strategy (e.g., const or probabilistic)
    samplingParam: 1.0  # Sampling rate (1.0 = 100% of requests traced)
    traceContextHeaderName: uber-trace-id  # Header used for trace context propagation
