services:
  ssh-port-tunnel:
    image: alpine:latest
    container_name: ssh-port-tunnel
    restart: unless-stopped
    networks:
      - nat
    ports:
      - "your-port:your-port"
    command:
      - sh
      - -c
      - >
        apk add --no-cache openssh-client &&
        cp /keys/id_rsa /tmp/id_rsa &&
        chmod 600 /tmp/id_rsa &&
        ssh -o StrictHostKeyChecking=no
        -o ExitOnForwardFailure=yes
        -i /tmp/id_rsa
        -N
        -g
        -L 0.0.0.0:18790:127.0.0.1:your-port
        root@host-ip-address
    volumes:
      - ./id_rsa:/keys/id_rsa:ro
#    labels: # (optional only for using traefik) ------>
#      - "traefik.enable=true"
#      - "traefik.http.routers.ssh-port-tunnel.entrypoints=websecure"
#      - "traefik.http.routers.ssh-port-tunnel.rule=Host(`ssh-port-tunnel.example.com`)" # Replace with your desired hostname
#      - "traefik.http.routers.ssh-port-tunnel.tls=true"
#      - "traefik.http.routers.ssh-port-tunnel.tls.certresolver=cloudflare" # Replace with your cert resolver name
#      - "traefik.http.services.ssh-port-tunnel.loadbalancer.server.port=your-port"    
#      - "traefik.docker.network=nat" 
#      - "traefik.http.routers.ssh-port-tunnel.service=ssh-port-tunnel"  
networks:
  nat:
    external: true
