services:
  changedetection:
    image: dgtlmoon/changedetection.io:0.49.3
    container_name: changedetection
    hostname: changedetection
    environment:
      # - BASE_URL=https://mysite.com # configure this for your own domain
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000
    volumes:
      - ./data/datastore:/datastore
#    ports:
#      - 5000:5000
    networks:
      - nat
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.changedetection.entrypoints=websecure"
      - "traefik.http.routers.changedetection.rule=Host(`change.example.com`)" # Replace with your desired hostname
      - "traefik.http.routers.changedetection.tls=true"
      - "traefik.http.routers.changedetection.tls.certresolver=cloudflare" # Replace with your cert resolver name
      - "traefik.http.services.changedetection.loadbalancer.server.port=5000"       
      - "traefik.docker.network=nat" 
      - "traefik.http.routers.changedetection.service=changedetection"
###################################################################################
  playwright-chrome:
    hostname: changedetection-chrome
    image: browserless/chrome
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - ENABLE_DEBUGGER=false
      - PREBOOT_CHROME=true
      - CONNECTION_TIMEOUT=300000
      - MAX_CONCURRENT_SESSIONS=10
      - CHROME_REFRESH_TIME=600000
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_STEALTH=true
      # Ignore HTTPS errors, like for self-signed certs
      - DEFAULT_IGNORE_HTTPS_ERRORS=true    
    networks:
      - nat
    restart: unless-stopped      
networks:
    nat:
        external: true    