services:
  shlink:
    image: shlinkio/shlink:stable
    pull_policy: always
    container_name: shlink
    restart: unless-stopped
#    user: root # optional
    ports:
      - "8080:8080"
    networks:
      - nat
    environment:
      - INITIAL_API_KEY=${INITIAL_API_KEY}
      - DEFAULT_DOMAIN=${DEFAULT_DOMAIN}
      # Note: you should also update SHLINK_SERVER_URL in the shlink-web service.
      - IS_HTTPS_ENABLED=false
      - PUID=1000
      - PGID=1000
    volumes:
      - ./shlink-data:/etc/shlink/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/rest/v3/health"]
      interval: 30s
      timeout: 10s
      retries: 3
#    labels:  # (optional only for using traefik) ---->
#      - "traefik.enable=true"
#      - "traefik.http.routers.shlink.entrypoints=websecure"
#      - "traefik.http.routers.shlink.rule=Host(`shlink.example.com`)" # Replace with your desired hostname
#      - "traefik.http.routers.shlink.tls=true"
#      - "traefik.http.routers.shlink.tls.certresolver=cloudflare" # Replace with your cert resolver name
#      - "traefik.http.services.shlink.loadbalancer.server.port=8080"    
#      - "traefik.docker.network=nat" 
#      - "traefik.http.routers.shlink.service=shlink"  
#      - "com.centurylinklabs.watchtower.enable=true"  # (optional if using watchtower for updates)
################################################################      
  shlink-web:
    image: shlinkio/shlink-web-client
    pull_policy: always
    container_name: shlink-web
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - nat
    environment:
      - SHLINK_SERVER_API_KEY=${INITIAL_API_KEY}
      # Note: if you've set IS_HTTPS_ENABLED=true, change http to https.
      - SHLINK_SERVER_URL=http://${DEFAULT_DOMAIN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
#    labels:  # (optional only for using traefik) ---->
#      - "traefik.enable=true"
#      - "traefik.http.routers.shlink-web.entrypoints=websecure"
#      - "traefik.http.routers.shlink-web.rule=Host(`shlink-web.example.com`)" # Replace with your desired hostname
#      - "traefik.http.routers.shlink-web.tls=true"
#      - "traefik.http.routers.shlink-web.tls.certresolver=cloudflare" # Replace with your cert resolver name
#      - "traefik.http.services.shlink-web.loadbalancer.server.port=8080"    
#      - "traefik.docker.network=nat" 
#      - "traefik.http.routers.shlink-web.service=shlink-web"  
#      - "com.centurylinklabs.watchtower.enable=true"  # (optional if using watchtower for updates)
################################################################      
networks:
  nat:
    external: true
