services:
  bolt.diy:
    image: registry.neurolearninglabs.com/code-labz/bolt-diy:latest
    restart: unless-stopped
#    ports:
#      - '5173:5173'
    environment:
      - NODE_ENV=production
      - COMPOSE_PROFILES=production
      # No strictly needed but serving as hints for Coolify
      - PORT=5173
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HuggingFace_API_KEY=${HuggingFace_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}
      - XAI_API_KEY=${XAI_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - TOGETHER_API_BASE_URL=${TOGETHER_API_BASE_URL}
      - AWS_BEDROCK_CONFIG=${AWS_BEDROCK_CONFIG}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - RUNNING_IN_DOCKER=true
    command: pnpm run dockerstart
    networks:
      - nat
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bolt-diy.entrypoints=websecure"
      - "traefik.http.routers.bolt-diy.rule=Host(`bolt-diy.example.com`)" # Replace with your desired hostname
      - "traefik.http.routers.bolt-diy.tls=true"
      - "traefik.http.routers.bolt-diy.tls.certresolver=cloudflare" # Replace with your cert resolver name
      - "traefik.http.services.bolt-diy.loadbalancer.server.port=5173"       
      - "traefik.docker.network=nat" 
      - "traefik.http.routers.bolt-diy.service=bolt-diy"
networks:
  nat:
    external: true
