services:
  code-server:
    image: otakulabz/codeserver-docker:latest
    container_name: code-server
    user: root
    environment:
      - TZ=AMERICA/LOS_ANGELOS
      - PASSWORD=${PASSWORD} #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
    #  - PROXY_DOMAIN=codeserver.example.com #optionall
    volumes:
      - ./config:/config
      - ./workspace:/home/coder/code-server
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - nat
#    labels: # (optional only for using traefik) ------>
#      - "traefik.enable=true"
#      - "traefik.http.routers.codeserver.entrypoints=websecure"
#      - "traefik.http.routers.codeserver.rule=Host(`codeserver.example.com`)" # Replace with your desired hostname
#      - "traefik.http.routers.codeserver.tls=true"
#      - "traefik.http.routers.codeserver.tls.certresolver=cloudflare" # Replace with your cert resolver name
#      - "traefik.http.services.codeserver.loadbalancer.server.port=your-port"    
#      - "traefik.docker.network=nat" 
#      - "traefik.http.routers.codeserver.service=codeserver"  
#      - "com.centurylinklabs.watchtower.enable=true"  # (optional if using watchtower for updates)
#      - "traefik.http.routers.codeserver.middlewares=authentik@file" # (optional if using authentik or basic auth to protect your site)
networks:
  nat:
    external: true