services:
  changedetection:
    image: dgtlmoon/changedetection.io:0.49.3
    container_name: changedetection
    hostname: changedetection
    environment:
#      - BASE_URL=https://change-detection.example.com # configure this for your own domain
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000
    volumes:
      - ./data/datastore:/datastore
    ports:
      - 5000:5000
    networks:
      - nat
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 1m
      timeout: 10s
      retries: 3
    depends_on:
      playwright-chrome:
        condition: service_healthy
#    labels: # (optional only for using traefik) ------>
#      - "traefik.enable=true"
#      - "traefik.http.routers.change-detection.entrypoints=websecure"
#      - "traefik.http.routers.change-detection.rule=Host(`change-detection.example.com`)" # Replace with your desired hostname
#      - "traefik.http.routers.change-detection.tls=true"
#      - "traefik.http.routers.change-detection.tls.certresolver=cloudflare" # Replace with your cert resolver name
#      - "traefik.http.services.change-detection.loadbalancer.server.port=5000"    
#      - "traefik.docker.network=nat" 
#      - "traefik.http.routers.change-detection.service=change-detection"  
#      - "com.centurylinklabs.watchtower.enable=true"  # (optional if using watchtower for updates)
#      - "traefik.http.routers.change-detection.middlewares=authentik@file" # (optional if using authentik or basic auth to protect your site)
###################################################################################
  playwright-chrome:
    hostname: changedetection-chrome
    image: browserless/chrome:latest
    restart: unless-stopped
    ports:
      - 3000
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - ENABLE_DEBUGGER=false
      - PREBOOT_CHROME=true
      - CONNECTION_TIMEOUT=300000
      - MAX_CONCURRENT_SESSIONS=10
      - CHROME_REFRESH_TIME=600000
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_STEALTH=true
      # Ignore HTTPS errors, like for self-signed certs
      - DEFAULT_IGNORE_HTTPS_ERRORS=true    
    networks:
      - nat
    restart: unless-stopped  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m
      timeout: 10s
      retries: 3    
networks:
  nat:
    external: true    