services:
  code-server:
    image: otakulabz/codeserver-docker:latest
    container_name: code-server
    user: root
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=AMERICA/LOS_ANGELOS
      - PASSWORD=${PASSWORD} #optional
      # - HASHED_PASSWORD=${HASHED_PASSWORD} #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
      # - SUDO_PASSWORD_HASH=${SUDO_PASSWORD_HASH} #optional
    #  - PROXY_DOMAIN=code-server.my.domain #optional
    #  - DEFAULT_WORKSPACE=/home/coder #optional
    volumes:
      - /path/to/code-server/config:/config
      - /path/to/workspace:/home/coder
  #  ports:
  #    - 8080:8080
    restart: unless-stopped
    networks:
      - nat
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.rule=Host(`code-server.my.domain`)"
      - "traefik.http.routers.code-server.entrypoints=web,websecure"
      - "traefik.http.routers.code-server.tls=true"
      - "traefik.http.routers.code-server.tls.certresolver=myresolver" # Replace 'myresolver' with your actual cert resolver name
      - "traefik.http.services.code-server.loadbalancer.server.port=8080"

networks:
  nat:
    external: true