services:
  homepage:
    image: ghcr.io/gethomepage/homepage:nightly
    container_name: homepage
    environment:
      PUID: 1000 # optional, your user id
      PGID: 1000 # optional, your group id
    volumes:
      - /config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
    networks:
      - nat
    ports:
      - 3000:3000 
network:
  nat:
    external: true                