---
services:
  gitlab:
    image: gitlab/gitlab-ce:17.9.1-ce.0
    container_name: gitlab
    shm_size: '256m'
    environment: {}
    networks:
      - nat
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    ports:
      - "80:80"
      - "443:443"
      - '2424:22'
    restart: unless-stopped

networks:
  nat:
    external: true