services:
  comfyui:
    image: yanwk/comfyui-boot:cu118-megapak
    container_name: comfyui
    restart: unless-stopped
#    ports:
#      - "8188:8188"
    volumes:
      - ./storage:/root
    environment:
      - CLI_ARGS=""
    networks:
      - nat
    extends:
      file: ./gpu.yml
      service: comfyui
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.comfyui.entrypoints=websecure"
      - "traefik.http.routers.comfyui.rule=Host(`comfyui.yourdomain.com`)" # Replace with your desired hostname
      - "traefik.http.routers.comfyui.tls=true"
      - "traefik.http.routers.comfyui.tls.certresolver=cloudflare" # Replace with your cert resolver name
      - "traefik.http.services.comfyui.loadbalancer.server.port=8188"    
      - "traefik.docker.network=nat" 
      - "traefik.http.routers.comfyui.service=comfyui"  
networks:
  nat:
    external: true      