services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:2.12.3'
    container_name: nginx-traefik
    networks:
      -  nat
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /data:/data
      - /letsencrypt:/etc/letsencrypt
networks:
    nat:
        external: true