services:
  socat:
    image: alpine/socat
    restart: always
    command: TCP-LISTEN:2376,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    container_name: socat-docker
    networks:
      - nat
    labels:
      - "traefik.enable=true"
      # Define a TCP router with HostSNI to match the domain
      - "traefik.tcp.routers.socat.rule=HostSNI(`example.com`)"  # Replace with your domain
      - "traefik.tcp.routers.socat.entrypoints=socat"            # Bind to the socat entrypoint
      # Enable TLS with Cloudflare as the certificate resolver
      - "traefik.tcp.routers.socat.tls=true"
      - "traefik.tcp.routers.socat.tls.certresolver=cloudflare"
      # Define the service and the forwarded port
      - "traefik.tcp.services.socat.loadbalancer.server.address=unix:///var/run/docker.sock"
      - "traefik.docker.network=nat"  # Ensure it's on the correct network
networks:
  nat:
    external: true
