services:
  lightrag:
    container_name: lightrag
    image: otakulabz/lightrag:latest
    pull_policy: always
    networks:
      - nat
#    ports:
#      - "9621:9621"
    volumes:
      - ./data/rag_storage:/app/data/rag_storage
      - ./data/inputs:/app/data/inputs
      - ./data/tiktoken:/app/data/tiktoken
#      - ./config.ini:/app/config.ini  # Un-comment this line if you have a config.ini file for customizing database
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - TIKTOKEN_CACHE_DIR=/app/data/tiktoken
    restart: unless-stopped
    labels:  # optional for traefik
      - "traefik.enable=true"
      - "traefik.http.routers.lightrag.entrypoints=websecure"
      - "traefik.http.routers.lightrag.rule=Host(`lightrag.example.com`)" # Replace with your desired hostname
      - "traefik.http.routers.lightrag.tls=true"
      - "traefik.http.routers.lightrag.tls.certresolver=cloudflare" # Replace with your cert resolver name
      - "traefik.http.services.lightrag.loadbalancer.server.port=9621"    
      - "traefik.docker.network=nat" 
#      - "traefik.http.services.lightrag.loadbalancer.server.scheme=https" # (optional, to set the scheme for your router if you want http or https)
      - "traefik.http.routers.lightrag.service=lightrag"  
networks:
  nat:
    external: true
