services:
  portainer:
    image: portainer/portainer-ce:latest
    pull: always
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /path/to/your/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nat
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 10s
      timeout: 3s
      retries: 3
#    labels: # (optional only for using traefik) ------> 
#      - "traefik.enable=true"
#      - "traefik.http.routers.portainer.entrypoints=websecure"
#      - "traefik.http.routers.portainer.rule=Host(`portainer.example.com`)" # Replace with your desired hostname
#      - "traefik.http.routers.portainer.tls=true"
#      - "traefik.http.routers.portainer.tls.certresolver=cloudflare" # Replace with your cert resolver name
#      - "traefik.http.services.portainer.loadbalancer.server.port=9000"    
#      - "traefik.docker.network=nat" 
#      - "traefik.http.routers.portainer.service=portainer"  
#      - "com.centurylinklabs.watchtower.enable=true"  # (optional if using watchtower for updates)
#      - "traefik.http.routers.portainer.middlewares=authentik@file" # (optional if using authentik or basic auth to protect your site)
networks:
  nat:
    external: true
