services:
  netbird:
    image: 'netbirdio/netbird:latest'
    container_name: netbird
    restart: unless-stopped
#    hostname: netbird  #(optional) changes your name inside netbird ui 
    environment:
#      - 'NB_MANAGEMENT_URL=https://yournetbird.com' #(optional) only if you self host your own netbird server
      - NB_SETUP_KEY=${NB_SETUP_KEY}
    volumes:
      - 'netbird-client:/etc/netbird'
    networks:
      - nat
    cap_add:
      - NET_ADMIN
#################################################################################################      
  socat:
    image: alpine/socat
    container_name: socat
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: TCP-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    restart: always
    network_mode: service:netbird
############################    
networks:
    nat:
      external: true