services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /path/to/your/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nat
networks:
  nat:
    external: true
