services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
    networks:
      - nat
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.qdrant.entrypoints=websecure"
#      - "traefik.http.routers.qdrant.rule=Host(`qdrant.yourdomain.com`)" # Replace with your desired hostname
#      - "traefik.http.routers.qdrant.tls=true"
#      - "traefik.http.routers.qdrant.tls.certresolver=cloudflare" # Replace with your cert resolver name
#      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"    
#      - "traefik.docker.network=nat" 
#      - "traefik.http.routers.qdrant.service=qdrant"  # Replace with your service name
########################################################################################################      
#      - "traefik.http.routers.qdrant-grpc.entrypoints=websecure"
#      - "traefik.http.routers.qdrant-grpc.rule=Host(`qdrant.yourdomain.com`)" # Replace with your desired hostname
#      - "traefik.http.routers.qdrant-grpc.tls=true"
#      - "traefik.http.routers.qdrant-grpc.tls.certresolver=cloudflare" # Replace with your cert resolver name
#      - "traefik.http.services.qdrant-grpc.loadbalancer.server.port=6334"    
#      - "traefik.docker.network=nat" 
#      - "traefik.http.routers.qdrant-grpc.service=qdrant-grpc"  # Replace with your service name
networks:
  nat:
    external: true      
