services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    pull_policy: always
    container_name: nextcloud
#    user: "root"  #uncomment if you want to run as root
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 443:443
    networks:
      - nat
    restart: unless-stopped  
#    labels:    
#      - "traefik.enable=true"
#      - "traefik.http.routers.nextcloud.entrypoints=websecure"
#      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.yourdomain.com`)"
#      - "traefik.http.routers.nextcloud.tls=true"
#      - "traefik.http.routers.nextcloud.tls.certresolver=cloudflare"
#      - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
#      - "traefik.docker.network=nat"
#      - "traefik.http.routers.nextcloud.service=nextcloud"
#      - "com.centurylinklabs.watchtower.enable=true"  # (optional if using watchtower for updates)
#      - "traefik.http.routers.nextcloud.middlewares=authentik@file" # (optional if using authentik or basic auth to protect your site)
#################################################################################
networks:
  nat:
    external: true