labels:
  - "traefik.http.middlewares.your-service-redirect.redirectregex.regex=^https://example.com/?$$"
  - "traefik.http.middlewares.your-service-redirect.redirectregex.replacement=https://example.com/your-path"
  - "traefik.http.routers.your-router.middlewares=your-service-redirect" #redirect your to the url of your choice with a custom path
