labels:
    - "traefik.enable=true"
    - "traefik.http.routers.your-router.entrypoints=websecure"
    - "traefik.http.routers.your-router.rule=Host(`example.com`)" # Replace with your desired hostname
    - "traefik.http.routers.your-router.tls=true"
    - "traefik.http.routers.your-router.tls.certresolver=cloudflare" # Replace with your cert resolver name
    - "traefik.http.services.your-router.loadbalancer.server.port=your-port"       
    - "traefik.docker.network=nat" 
    - "traefik.http.routers.your-router.service=service-name"
