services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.03.0
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
  #  ports:
  #    - "53:53/tcp"
  #    - "53:53/udp"
  #    - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
  #    - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - '/etc:/etc/pihole'
      - '/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: always
#    network_mode: host
    networks:
      -  nat
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.rule=Host(`example.com`)" # Replace with your desired hostname
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=cloudflare" # Replace with your cert resolver name
      - "traefik.http.middlewares.pihole-stripprefix.stripprefix.prefixes=/admin"
      - "traefik.http.routers.pihole-stripprefix.middlewares=pihole-stripprefix@docker"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
networks:
    nat:
        external: true