services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./data:/data #optional
    ports:
      - 5000:5000
    restart: unless-stopped
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.kavita.entrypoints=websecure"
#      - "traefik.http.routers.kavita.rule=Host(`kavita.yourdomain.com`)" # Replace with your desired hostname
#      - "traefik.http.routers.kavita.tls=true"
#      - "traefik.http.routers.kavita.tls.certresolver=letsencrypt" # Replace with your cert resolver name
#      - "traefik.http.services.kavita.loadbalancer.server.port=5000"    
#      - "traefik.docker.network=nat" 
#      - "traefik.http.routers.kavita.service=kavita"  
    networks:
      - nat
networks:
  nat:
    external: true