services:
  web:
    image: ghcr.io/dsgnr/portcheckerio-web:latest
    container_name: portchecker
    restart: unless-stopped
    environment:
      - DEFAULT_PORT=443  # Optional
    depends_on:
      - api
    networks:
      - nat
    ports:
      - 8080:80 
#################################################################
  api:
    image: ghcr.io/dsgnr/portcheckerio-api:latest
    container_name: portchecker_api
    restart: unless-stopped
    ports:
     - 8000:8000
    networks:
      - nat
networks:
  nat:
    external: true