services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - nat
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/radarr/data:/config
      - /path/to/movies:/movies #optional
      - /path/to/download-client-downloads:/downloads #optional
#    ports:
#      - 7878:7878
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.rule=Host(`radarr.yourdomain.com`)" # Replace with your desired hostname
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=cloudflare" # Replace with your cert resolver name
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"    
      - "traefik.docker.network=nat" 
      - "traefik.http.routers.radarr.service=radarr"  
#      - "com.centurylinklabs.watchtower.enable=true"  # (optional if using watchtower for updates)
#      - "traefik.http.routers.radarr.middlewares=authentik@file" # (optional if using authentik or basic auth to protect your site)
networks:
  nat:
    external: true      