services:
  nexterm:
    container_name: terminal
    restart: unless-stopped
    volumes:
      - /terminal:/app/data
    image: germannewsmaker/nexterm:1.0.2-OPEN-PREVIEW
    networks:
      - nat
    ports:
      - 6989:6989         
network:
  nat:
    external: true      