services:
  teleport:
    image: public.ecr.aws/gravitational/teleport:17.2.8
    container_name: teleport
    ports:
      - "3080:3080"
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lib/teleport
     networks:
       - your-traefik-network
    restart: unless-stopped