services:
  dockge:
    image: louislam/dockge:nightly
    restart: unless-stopped
    container_name: dockge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/data:/app/data
      - ./root/docker/:/root/.docker
      - ./opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks
    ports:
      - 5001:5001
    networks:
      -  nat
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 1m
      timeout: 10s
      retries: 3
#    labels: # (optional only for using traefik) ------>
#      - "traefik.enable=true"
#      - "traefik.http.routers.dockge.entrypoints=websecure"
#      - "traefik.http.routers.dockge.rule=Host(`dockge.example.com`)" # Replace with your desired hostname
#      - "traefik.http.routers.dockge.tls=true"
#      - "traefik.http.routers.dockge.tls.certresolver=cloudflare" # Replace with your cert resolver name
#      - "traefik.http.services.dockge.loadbalancer.server.port=5001"    
#      - "traefik.docker.network=nat" 
#      - "traefik.http.routers.dockge.service=dockge"  
#      - "com.centurylinklabs.watchtower.enable=true"  # (optional if using watchtower for updates)
#      - "traefik.http.routers.dockge.middlewares=authentik@file" # (optional if using authentik or basic auth to protect your site)
networks:
  nat:
    external: true