services:
  mixpost:
    image: 'inovector/mixpost:v2.1.2'
    container_name: mixpost
    restart: unless-stopped
    environment:
      APP_NAME: Mixpost
      APP_KEY: '${SERVICE_BASE64_MIXPOST}'
      APP_DEBUG: false
      APP_DOMAIN: '${SERVICE_URL_MIXPOST}'
      APP_URL: '${SERVICE_FQDN_MIXPOST}'
      DB_DATABASE: '${MIXPOST_MYSQL_DATABASE:-mixpost_db}'
      DB_USERNAME: '${MIXPOST_SERVICE_USER_MYSQL}'
      DB_PASSWORD: '${MIXPOST_SERVICE_PASSWORD_MYSQL}'
      SSL_EMAIL: '${SSL_EMAIL:-user@example.com}'
    volumes:
      - '/mixpost/app:/var/www/html/storage/app'
      - '/mixpost/logs:/var/www/html/storage/logs'
    depends_on:
      mysql:
        condition: service_healthy
      redis-mixpost:
        condition: service_healthy
    networks:
      - nat
      - nat2
    ports:
      - 80:80
#########################################################################################################
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql_mixpost
    restart: always
    environment:
      MYSQL_DATABASE: '${MIXPOST_MYSQL_DATABASE:-mixpost_db}'
      MYSQL_USER: '${MIXPOST_SERVICE_USER_MYSQL}'
      MYSQL_PASSWORD: '${MIXPOST_SERVICE_PASSWORD_MYSQL}'
      MYSQL_ROOT_PASSWORD: '${MIXPOST_SERVICE_PASSWORD_MYSQLROOT}'
    volumes:
      - '/mixpost/mysql:/var/lib/mysql'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - 127.0.0.1
        - '-uroot'
        - '-p'
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
      - nat2
###########################################################################################################
  redis: # Renamed service for clarity
    image: 'redis:alpine'
    container_name: redis_mixpost_app # Renamed container for clarity
    restart: always
    healthcheck:
      test:
        - CMD
        - redis-cli
        - '--raw'
        - incr
        - ping
    networks:
      - nat2        
#########################################################################################################        
networks:
  nat:
    external: true
  nat2:
    external: true    