services:
  registry-ui:
    image: quiq/registry-ui:latest
    container_name: registry_ui
    restart: unless-stopped
    environment:
      - X-WEBAUTH-USER=${X-WEBAUTH-USER}
    networks:
      -  nat
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry-ui.entrypoints=websecure"
      - "traefik.http.routers.registry-ui.rule=Host(`example.com`)" # Replace with your desired hostname
      - "traefik.http.routers.registry-ui.tls=true"
      - "traefik.http.routers.registry-ui.tls.certresolver=cloudflare" # Replace with your cert resolver name
      - "traefik.http.services.registry-ui.loadbalancer.server.port=8000"
###################################################      
  registry-server:
    image: registry:latest
    restart: unless-stopped
    container_name: registry-server    
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"      
    volumes:
      - /path/to/your-containers:/var/lib/registry
      - /auth:/auth
    labels: # Labels for registry-server service
          - "traefik.enable=true"
          - "traefik.http.routers.registry-server.entrypoints=websecure"
          - "traefik.http.routers.registry-server.rule=Host(`example.com`)" # Replace with your desired hostname for registry API
          - "traefik.http.routers.registry-server.tls=true"
          - "traefik.http.routers.registry-server.tls.certresolver=cloudflare" # Replace with your cert resolver name
          - "traefik.http.services.registry-server.loadbalancer.server.port=5000" # Registry server port
    networks:
      -  nat
################################      
networks:
    nat:
        external: true