services:
  watchtower:
    container_name: watchtower
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    command: --interval 10 --http-api-metrics --http-api-token demotoken --debug parent child
    networks:
      - nat
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.watchtower.rule=Host(`watchtower.example.com`)" # Replace with your domain
      - "traefik.http.routers.watchtower.entrypoints=websecure"
      - "traefik.http.routers.watchtower.tls=true"
      - "traefik.http.routers.watchtower.tls.certresolver=cloudflare"
      - "traefik.http.services.watchtower.loadbalancer.server.port=8080"
##############################################################################################
  parent:
    image: nginx
    container_name: parent
    networks:
      - nat
    restart: always
    # No Traefik labels - kept internal
####################################
  child:
    image: nginx:alpine
    labels:
      com.centurylinklabs.watchtower.depends-on: parent
    container_name: child
    networks:
      - nat
    restart: always
    # No Traefik labels - kept internal
################################################################
networks:
  nat:
    external: true